{"uuid": "edc654eb-8261-41bd-b536-643fcb57cf9c", "children": ["3aef8e06-9104-4341-9221-80da20961442"], "befores": [{"name": "Авторизация юзера", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class=\"button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa\"> is not clickable at point (640,549) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 884, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\conftest.py\", line 49, in authorize_user\n    login_page.fill_user_data_form(registered_user['email'], registered_user['password'])\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\pages\\login_page.py\", line 20, in fill_user_data_form\n    self.click_on_element(LoginPageLocators.LOGIN_BUTTON)\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\pages\\base_page.py\", line 18, in click_on_element\n    self.driver.find_element(*locator).click()\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Заполнение формы авторизации пользователя", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class=\"button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa\"> is not clickable at point (640,549) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:337:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:205:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:85:31\n\n", "trace": "  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\pages\\login_page.py\", line 20, in fill_user_data_form\n    self.click_on_element(LoginPageLocators.LOGIN_BUTTON)\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\pages\\base_page.py\", line 18, in click_on_element\n    self.driver.find_element(*locator).click()\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\ramms\\PycharmProjects\\Diplom\\Diplom_3\\Diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Заполнение поля \"Почты\" ", "status": "passed", "parameters": [{"name": "email", "value": "'7dzwbt4ngr@yandex.ru'"}], "start": 1728660408901, "stop": 1728660409001}, {"name": "Заполнение поля \"Пароль\"", "status": "passed", "parameters": [{"name": "password", "value": "'gx4estnamo'"}], "start": 1728660409001, "stop": 1728660409043}], "parameters": [{"name": "email", "value": "'7dzwbt4ngr@yandex.ru'"}, {"name": "password", "value": "'gx4estnamo'"}], "start": 1728660408901, "stop": 1728660409062}], "start": 1728660403099, "stop": 1728660409064}], "start": 1728660403099, "stop": 1728660409098}